version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: stocks_db
    ports:
      - "8200:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8101:8080"